#!/usr/bin/env python3
# Tests for the G-code preprocessor (stdlib only)
#
# Run from the repository root:
#   python3 -m unittest discover -s tests -v

import importlib
import logging
import os
import shutil
import subprocess
import sys
import tempfile
import time
import unittest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXTRAS = os.path.join(REPO, 'klipper', 'extras')
sys.path.append(EXTRAS)
sys.path.append(os.path.join(REPO, 'klipper'))

from gcode_preprocessor_base import (  # noqa: E402
    GcodePatterns, PreprocessorContext, ProcessorConfig, run_pipeline
)

LOG = logging.getLogger('test')
LOG.addHandler(logging.NullHandler())
LOG.propagate = False


def idle(**values):
    module = importlib.import_module('preprocessors.idle_tool_shutdown')
    return module.create_processor(ProcessorConfig('idle', values, LOG), LOG)


def tokens(**values):
    module = importlib.import_module('preprocessors.token_replacer')
    return module.create_processor(ProcessorConfig('tokens', values, LOG), LOG)


class PipelineTestCase(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmpdir)

    def write(self, text, name='test.gcode', mode='w'):
        path = os.path.join(self.tmpdir, name)
        with open(path, mode) as f:
            f.write(text)
        return path

    def process(self, processors, text, name='test.gcode'):
        path = self.write(text, name)
        context = PreprocessorContext()
        context.file_path = path
        context.filename = name
        result = run_pipeline(path, processors, context, LOG)
        self.assertTrue(result['success'], result)
        with open(path) as f:
            return f.read().splitlines()


class TestIdleToolShutdown(PipelineTestCase):
    def test_end_of_use_cooldown(self):
        out = self.process([idle()], "T0\nG1 X1\nT1\nG1 X2\nT0\nG1 X3\n")
        self.assertEqual(out[out.index('T0', 4) + 1:][:2],
                         ['; T1 no longer needed - cooling down', 'M104 T1 S0'])

    def test_reselecting_active_tool_does_not_cool_it(self):
        out = self.process([idle()], "T0\nG1 X1\nT1\nG1 X2\nT1\nG1 X3\nT0\nG1 X4\n")
        second_t1 = [i for i, l in enumerate(out) if l == 'T1'][1]
        self.assertEqual(out[second_t1 + 1], 'G1 X3')
        self.assertEqual(out.count('M104 T1 S0'), 1)
        self.assertGreater(out.index('M104 T1 S0'), out.index('T0', second_t1))

    def test_exclude_tools(self):
        out = self.process([idle(exclude_tools='1')], "T0\nT1\nT0\nG1 X1\n")
        self.assertNotIn('M104 T1 S0', out)

    def test_tool_heaters_mapping(self):
        out = self.process([idle(tool_heaters='1=extruder3, T2:extruder4')],
                           "T0\nT1\nT2\nT0\nG1 X1\n")
        self.assertIn('SET_HEATER_TEMPERATURE HEATER=extruder3 TARGET=0', out)
        self.assertIn('SET_HEATER_TEMPERATURE HEATER=extruder4 TARGET=0', out)
        self.assertNotIn('M104 T1 S0', out)

    def test_predictive_cooldown_rearms_after_reselect(self):
        # each block moves 100 mm at F60 = 100 s, timeout 1 min
        block = "G1 X100 F60\nG1 X0\n"
        gcode = ("T0\n" + block + "T1\n" + block + block + "T0\nM104 S220\n" + block +
                 "T1\n" + block + block + "T0\n" + block + "T1\nG1 X1\n")
        out = self.process([idle(idle_timeout_minutes='1')], gcode)
        idle_lines = [l for l in out if 'will be idle' in l]
        # both tools are predicted idle twice (re-armed when selected again)
        self.assertEqual(sum('T0 will be idle' in l for l in idle_lines), 2)
        self.assertEqual(sum('T1 will be idle' in l for l in idle_lines), 2)

    def test_state_reset_between_files(self):
        processor = idle()
        self.process([processor], "T2\nG1 X1\n", 'a.gcode')
        out = self.process([processor], "T2\nG1 X1\nT0\nG1 X2\n", 'b.gcode')
        self.assertEqual(out.count('M104 T2 S0'), 1)

    def test_time_estimation(self):
        processor = idle(idle_timeout_minutes='100')
        gcode = ("G90\nG1 X100 Y0 F6000\n"     # 100 mm absolute -> 1 s
                 "G91\nG1 X10\nG90\n"          # 10 mm relative -> 0.1 s
                 "G2 X100 Y0 I-50 J0\n"        # full circle r=50 -> 3.1416 s
                 "G4 S5 ; Pause\n"             # 5 s, comment ignored
                 "G4 P500\n"                   # 0.5 s
                 "G92 X0\nG1 X10\n"            # 10 mm after G92 -> 0.1 s
                 "T0\n")
        path = self.write(gcode)
        processor.pre_process(path, PreprocessorContext())
        self.assertAlmostEqual(list(processor.toolchange_times.values())[0],
                               1 + 0.1 + 3.14159 + 5 + 0.5 + 0.1, places=3)


class TestTokenReplacer(PipelineTestCase):
    GCODE = ("; generated by OrcaSlicer 2.3.0\n"
             "PRINT_START BED=\"!!curr_bed_type!!\" N=!tool_count! C=!colors! "
             "MAT=!!filament_type!! COL=!!filament_colour!! T=!!tools!!\n"
             "T0\nT1\n"
             "; curr_bed_type = Cool Plate\n"
             "; filament_colour = #FF0000;#00FF00\n"
             "; filament_type = PLA;PETG\n"
             "; filament_settings_id = \"Generic PLA\";\"Generic PETG\"\n")

    def test_replacement_and_sanitizing(self):
        out = self.process([tokens()], self.GCODE)
        self.assertEqual(out[2], 'PRINT_START BED="Cool Plate" N=2 C=FF0000,00FF00 '
                                 'MAT=PLA,PETG COL=FF0000,00FF00 T=!!tools!!')

    def test_sanitizing_can_be_disabled(self):
        out = self.process([tokens(sanitize_generic_values='False')], self.GCODE)
        self.assertIn('MAT=PLA;PETG', out[2])

    def test_boolean_options(self):
        out = self.process([tokens(replace_placeholders='False')], self.GCODE)
        self.assertIn('N=!tool_count!', out[2])

    def test_filament_names(self):
        processor = tokens(extract_filament_names='True')
        out = self.process([processor], self.GCODE + "M118 !filament_names!\n")
        self.assertEqual(out[-1], 'M118 Generic PLA,Generic PETG')

    def test_state_reset_between_files(self):
        processor = tokens()
        self.process([processor], self.GCODE, 'a.gcode')
        out = self.process([processor],
                           "PRINT_START BED=!!curr_bed_type!! N=!tool_count! C=!colors!\n"
                           "T3\n; curr_bed_type = Textured PEI Plate\n"
                           "; filament_colour = #0000FF\n", 'b.gcode')
        self.assertEqual(out[1], 'PRINT_START BED=Textured PEI Plate N=1 C=0000FF')


class TestBase(PipelineTestCase):
    def test_tool_number_patterns(self):
        cases = {'T3': 3, 'T3 ; comment': 3, 'SELECT_TOOL T=2': 2, 'SELECT_TOOL TOOL=4': 4,
                 'SELECT_TOOL TOOL=T1': 1, 'SELECT_TOOL TOOL=nozzle': None,
                 'MMU_CHANGE_TOOL TOOL=5': 5, 'G1 X1': None, '; T1': None}
        for line, expected in cases.items():
            self.assertEqual(GcodePatterns.extract_tool_number(line), expected, line)

    def test_config_values(self):
        config = ProcessorConfig('x', {'a': ' yes ', 'b': 'nope', 'c': '2.5', 'D': '7'}, LOG)
        self.assertTrue(config.getboolean('a'))
        self.assertTrue(config.getboolean('b', True))
        self.assertEqual(config.getfloat('c'), 2.5)
        self.assertEqual(config.getint('d'), 7)
        self.assertEqual(config.getfloat('missing', 1.0), 1.0)

    def test_non_utf8_bytes_preserved(self):
        raw = b"; object \xe4\xf6\xfc\nT0\nT1\nT0\n"
        path = self.write(raw, mode='wb')
        context = PreprocessorContext()
        run_pipeline(path, [idle()], context, LOG)
        with open(path, 'rb') as f:
            self.assertIn(b"\xe4\xf6\xfc", f.read())
        self.assertFalse(os.path.exists(path + '.preprocessing'))

    def test_not_processed_twice(self):
        path = self.write("T0\nT1\nT0\n")
        run_pipeline(path, [idle()], PreprocessorContext(), LOG)
        result = run_pipeline(path, [idle()], PreprocessorContext(), LOG)
        self.assertFalse(result['processed'])

    def test_fingerprint_with_slicer(self):
        out = self.process([tokens()], "; generated by OrcaSlicer 2.3.0\nT0\n")
        self.assertEqual(out[0], '; processed by ktc-gcode preprocessor (slicer: OrcaSlicer)')

    def test_legacy_fingerprint_not_processed_again(self):
        path = self.write("; processed by klipper-gcode-preprocessor\nT0\nT1\nT0\n")
        result = run_pipeline(path, [idle()], PreprocessorContext(), LOG)
        self.assertFalse(result['processed'])

    def test_moonraker_ident_regex(self):
        import re
        sys.path.insert(0, os.path.join(REPO, 'moonraker'))
        try:
            regex = importlib.import_module('gcode_preprocessor').FINGERPRINT_REGEX
        finally:
            sys.path.pop(0)
        for line in ('; processed by ktc-gcode preprocessor (slicer: OrcaSlicer)',
                     '; processed by klipper-gcode-preprocessor'):
            self.assertIsNotNone(re.search(regex, 'x\n' + line + '\n', re.MULTILINE), line)


class TestMoonrakerScript(PipelineTestCase):
    SCRIPT = os.path.join(REPO, 'moonraker', 'gcode_preprocessor.py')

    def test_gcode_processor_mode_with_inline_comments(self):
        cfg = self.write("[gcode_preprocessor]\n"
                         "processors: token_replacer, idle_tool_shutdown  # order matters\n"
                         "[gcode_preprocessor idle_tool_shutdown]\n"
                         "exclude_tools: 0    # keep T0 hot\n"
                         "idle_timeout_minutes: 0 ; disabled\n"
                         "[gcode_preprocessor token_replacer]\n"
                         "replace_placeholders: False\n", 'preprocessor.cfg')
        gcode = self.write("M118 !tool_count!\nT0\nT1\nT0\nT1\nG1 X1\n")
        proc = subprocess.run([sys.executable, self.SCRIPT, '-C', cfg, '--gcode-file', gcode],
                              capture_output=True, text=True)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        with open(gcode) as f:
            out = f.read().splitlines()
        self.assertTrue(out[0].startswith('; processed by ktc-gcode preprocessor'))
        self.assertIn('M118 !tool_count!', out)
        self.assertNotIn('M104 T0 S0', out)


class TestMoonrakerConsoleMessages(PipelineTestCase):
    CFG = "[gcode_preprocessor]\nprocessors: idle_tool_shutdown\n"

    def run_upload(self, state, gcode="T0\nT1\nT0\n", cfg=None, fail=False):
        import asyncio
        sys.path.insert(0, os.path.join(REPO, 'moonraker'))
        try:
            component = importlib.import_module('gcode_preprocessor')
        finally:
            sys.path.pop(0)
        cfg_path = self.write(self.CFG if cfg is None else cfg, 'preprocessor.cfg')
        self.write(gcode, 'upload.gcode')
        messages = []
        tmpdir = self.tmpdir

        class MetadataStorage:
            gc_path = tmpdir
            def register_gcode_processor(self, name, config):
                self.proc = config
            async def _run_extract_metadata(self, filename, ufp_path):
                if fail:
                    raise RuntimeError("metadata failed")
                component.preprocess_file(os.path.join(self.gc_path, filename), cfg_path)

        mdst = MetadataStorage()

        class EventLoop:
            async def run_in_thread(self, func, *args):
                return func(*args)

        class KlippyApis:
            async def query_objects(self, objects, default=None):
                return {'print_stats': {'state': state}}

        class Server:
            def lookup_component(self, name):
                if name == 'klippy_apis':
                    return KlippyApis()
                return type('FM', (), {'get_metadata_storage': lambda s: mdst})()
            def get_event_loop(self):
                return EventLoop()
            def send_event(self, event, *args):
                messages.append((event,) + args)

        class Config:
            def get_server(self):
                return Server()
            def getboolean(self, option, default):
                return default
            def get(self, option, default):
                return cfg_path if option == 'config_path' else default
            def getfloat(self, option, default, above=None):
                return default

        component.load_component(Config())
        try:
            asyncio.run(mdst._run_extract_metadata('upload.gcode', None))
        except RuntimeError:
            pass
        return [m[1] for m in messages if m[0] == 'server:gcode_response']

    def test_messages_when_idle(self):
        self.assertEqual(self.run_upload('standby'),
                         ['KTC preprocessing active', 'preprocessing successful'])

    def test_no_messages_while_printing(self):
        self.assertEqual(self.run_upload('printing'), [])
        self.assertEqual(self.run_upload('paused'), [])

    def test_no_messages_for_processed_file(self):
        self.assertEqual(self.run_upload('standby', "; processed by ktc-gcode preprocessor\nT0\n"), [])

    def test_no_messages_when_disabled(self):
        cfg = "[gcode_preprocessor]\nenabled: False  # off\nprocessors: idle_tool_shutdown\n"
        self.assertEqual(self.run_upload('standby', cfg=cfg), [])

    def test_failure_message(self):
        self.assertEqual(self.run_upload('complete', fail=True),
                         ['KTC preprocessing active', '!! KTC preprocessing failed - see moonraker.log'])


class FakeConfig:
    def __init__(self, printer, name, values):
        self.printer, self.name, self.values = printer, name, values

    def get_printer(self):
        return self.printer

    def get_name(self):
        return self.name

    def get(self, option, default=None):
        return self.values.get(option, default)

    def getboolean(self, option, default=None):
        value = self.values.get(option)
        return default if value is None else value.lower() in ('1', 'true', 'yes', 'on')

    def get_prefix_options(self, prefix):
        return [o for o in self.values if o.startswith(prefix)]


class FakeReactor:
    def monotonic(self):
        return time.monotonic()

    def pause(self, waketime):
        time.sleep(max(0., waketime - time.monotonic()))
        return time.monotonic()


class FakeGcode:
    def __init__(self):
        self.commands = {}

    def register_command(self, name, func, desc=None):
        self.commands[name] = func

    def respond_info(self, msg, log=True):
        pass


class FakePrinter:
    def __init__(self):
        self.objects = {'gcode': FakeGcode()}
        self.handlers = {}
        self.reactor = FakeReactor()

    def lookup_object(self, name, default=None):
        return self.objects.get(name, default)

    def register_event_handler(self, event, callback):
        self.handlers.setdefault(event, []).append(callback)

    def get_reactor(self):
        return self.reactor


@unittest.skipUnless(hasattr(os, 'fork'), "requires fork")
class TestKlipperModule(PipelineTestCase):
    def test_section_options_reach_processors(self):
        module = importlib.import_module('extras.gcode_preprocessor')
        printer = FakePrinter()
        section_name = 'gcode_preprocessor idle_tool_shutdown'
        printer.objects[section_name] = module.load_config_prefix(
            FakeConfig(printer, section_name, {'exclude_tools': '1', 'custom_option': 'x'}))
        main = module.load_config(FakeConfig(printer, 'gcode_preprocessor',
                                             {'processors': 'idle_tool_shutdown'}))
        for callback in printer.handlers['klippy:connect']:
            callback()
        self.assertEqual(main.processors[0].exclude_tools, {1})

        path = self.write("T0\nT1\nT2\nT0\nG1 X1\n")
        result = main.process_file(path)
        self.assertTrue(result['processed'], result)
        with open(path) as f:
            out = f.read().splitlines()
        self.assertIn('M104 T2 S0', out)
        self.assertNotIn('M104 T1 S0', out)


if __name__ == '__main__':
    unittest.main()
